[project]
name = "minishell"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "norminette>=3.3.55",
    "pre-commit>=4.0.1",
]
